### ISSUE TITLE
Crash in macOS 10.14.4

### ISSUE THREAD

**Issue by piaojin** [ReverseScale/FlutterMacApp#1]
Crash in macOS 10.14.4

Xcode: 
`10.2.1`

Flutter: 
```
Flutter 1.4.12 • channel dev • https://github.com/flutter/flutter.git
Framework • revision 294d7ea0cf (3 weeks ago) • 2019-04-08 12:37:43 -0700
Engine • revision ff1bcdc009
Tools • Dart 2.2.1 (build 2.2.1-dev.3.0 None)
```

<img width="1680" alt="WX20190426-232739@2x" src="https://user-images.githubusercontent.com/10163672/56818779-efcd0380-687a-11e9-940d-1987dc592374.png">

**Comment by ReverseScale** [comment]
Thank you very much, I just tried it. I really have this problem. I also feedback this question to the Feather platform. 

I feel that relying on this platform is always unstable, so I will follow 
https://github.com/google/flutter- Desktop-embedding/ 

The method here regenerates the macOS app. 

For a quick start, please see: https://github.com/google/flutter-desktop-embedding/blob/master/Quick-Start.md

**Comment by ReverseScale** [comment]
Hi, friend, I didn't wait for the reply from the Feather platform. But the surprise is that I found a new tool.
And it feels great, I also recommend you to try, I will update the article when I have time.
https://github.com/go-flutter-desktop/go-flutter

![WX20190428-152351@2x](https://user-images.githubusercontent.com/13606492/56860621-33cf1e00-69cb-11e9-807a-ba796e674d7f.png)
![WX20190428-152707@2x](https://user-images.githubusercontent.com/13606492/56860633-49444800-69cb-11e9-9a60-728e1eccf45f.png)
![WX20190428-152433@2x](https://user-images.githubusercontent.com/13606492/56860636-4e08fc00-69cb-11e9-8014-3d3e985fd07e.png)
![WX20190428-152503@2x](https://user-images.githubusercontent.com/13606492/56860638-52351980-69cb-11e9-8350-28c72973938a.png)

**Comment by piaojin** [comment]
@ReverseScale Cool thank you!
